name: Build gc

on:
  repository_dispatch:
  workflow_dispatch:
  
jobs:
  build-chroot:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install runner dependencies
      run: |
        sudo apt update
        sudo apt install -y qemu-user-static binfmt-support jq curl xz-utils grep coreutils

    - name: Prepare container rootfs
      run: |
        mkdir -p /opt/chroot
        curl -L -o /opt/chroot/rootfs.tar.xz https://images.linuxcontainers.org/images/ubuntu/jammy/armhf/default/20250715_08:28/rootfs.tar.xz
        mkdir -p /opt/chroot/rootfs
        sudo tar -xf /opt/chroot/rootfs.tar.xz -C /opt/chroot/rootfs
        rm /opt/chroot/rootfs.tar.xz
        sudo mkdir -p /opt/chroot/rootfs/gc
        sudo cp -r . /opt/chroot/rootfs/gc
        echo "Mounting system directories..."
        for dir in proc sys dev dev/pts; do
          sudo mkdir -p /opt/chroot/rootfs/$dir
          sudo mount --bind /$dir /opt/chroot/rootfs/$dir
        done

        echo "Copying qemu-arm-static into chroot..."
        sudo cp /usr/bin/qemu-arm-static /opt/chroot/rootfs/usr/bin/
        sudo rm /opt/chroot/rootfs/etc/resolv.conf
        sudo touch /opt/chroot/rootfs/etc/resolv.conf
        echo "nameserver 1.1.1.1" | sudo tee /opt/chroot/rootfs/etc/resolv.conf
        echo "nameserver 8.8.8.8" | sudo tee -a /opt/chroot/rootfs/etc/resolv.conf
        

    - name: Build gc
      run: |
        sudo chroot /opt/chroot/rootfs /bin/bash -c "
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y build-essential git autoconf automake libtool pkg-config zlib1g-dev libssl-dev libconfig-dev cmake binutils libselinux1 patchelf python3-pip python3-pyelftools scons
          pip3 install staticx
          git clone https://github.com/linux-usb-gadgets/libusbgx.git libusbgx
          cd /libusbgx
          git checkout 060784424609d5a4e3bce8355f788c93f09802a5
          autoreconf -i
          ./configure
          make
          make install
          ldconfig -n /usr/local/lib
          mkdir -p /artifacts/prebin
          mkdir -p /artifacts/bin
          mkdir -p /gc/build
          cd /gc/build
          cmake ..
          make
          LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib" ldd /gc/bin/gc
          cp /gc/bin/gc /artifacts/prebin
          staticx --strip /artifacts/prebin/gc /artifacts/bin/gc
          chmod 644 /artifacts/bin/gc
          find /artifacts
        "
          
    - name: Copy build artifacts from chroot
      run: |
        cp /opt/chroot/rootfs/artifacts/bin/gc .

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        name: "Release ${{ github.ref_name }}"
        artifacts: ./gc
        body: "✅ gc static armv7/armhf binaries only"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
